export const AVATAR_OPTIONS = [
    // Female / Feminine Style (Notionists)
    "https://api.dicebear.com/7.x/notionists/png?seed=Jessica",
    "https://api.dicebear.com/7.x/notionists/png?seed=Sophia",
    "https://api.dicebear.com/7.x/notionists/png?seed=Emma",
    "https://api.dicebear.com/7.x/notionists/png?seed=Olivia",
    "https://api.dicebear.com/7.x/notionists/png?seed=Ava",
    "https://api.dicebear.com/7.x/notionists/png?seed=Isabella",
    "https://api.dicebear.com/7.x/notionists/png?seed=Mia",
    "https://api.dicebear.com/7.x/notionists/png?seed=Charlotte",
    "https://api.dicebear.com/7.x/notionists/png?seed=Amelia",
    "https://api.dicebear.com/7.x/notionists/png?seed=Harper",
    "https://api.dicebear.com/7.x/notionists/png?seed=Evelyn",
    "https://api.dicebear.com/7.x/notionists/png?seed=Abigail",
    "https://api.dicebear.com/7.x/notionists/png?seed=Emily",
    "https://api.dicebear.com/7.x/notionists/png?seed=Elizabeth",
    "https://api.dicebear.com/7.x/notionists/png?seed=Sofia",
    "https://api.dicebear.com/7.x/notionists/png?seed=Ella",
    "https://api.dicebear.com/7.x/notionists/png?seed=Madison",
    "https://api.dicebear.com/7.x/notionists/png?seed=Scarlett",
    "https://api.dicebear.com/7.x/notionists/png?seed=Victoria",
    "https://api.dicebear.com/7.x/notionists/png?seed=Luna",

    // Male / Masculine Style (Notionists)
    "https://api.dicebear.com/7.x/notionists/png?seed=Liam",
    "https://api.dicebear.com/7.x/notionists/png?seed=Noah",
    "https://api.dicebear.com/7.x/notionists/png?seed=Oliver",
    "https://api.dicebear.com/7.x/notionists/png?seed=Elijah",
    "https://api.dicebear.com/7.x/notionists/png?seed=James",
    "https://api.dicebear.com/7.x/notionists/png?seed=William",
    "https://api.dicebear.com/7.x/notionists/png?seed=Benjamin",
    "https://api.dicebear.com/7.x/notionists/png?seed=Lucas",
    "https://api.dicebear.com/7.x/notionists/png?seed=Henry",
    "https://api.dicebear.com/7.x/notionists/png?seed=Alexander",
    "https://api.dicebear.com/7.x/notionists/png?seed=Michael",
    "https://api.dicebear.com/7.x/notionists/png?seed=Daniel",
    "https://api.dicebear.com/7.x/notionists/png?seed=Jacob",
    "https://api.dicebear.com/7.x/notionists/png?seed=Logan",
    "https://api.dicebear.com/7.x/notionists/png?seed=Jackson",
    "https://api.dicebear.com/7.x/notionists/png?seed=Sebastian",
    "https://api.dicebear.com/7.x/notionists/png?seed=Jack",
    "https://api.dicebear.com/7.x/notionists/png?seed=Aiden",
    "https://api.dicebear.com/7.x/notionists/png?seed=Owen",
    "https://api.dicebear.com/7.x/notionists/png?seed=Samuel"
];
